services:
  fastapi_app:
    build: .
    container_name: fastapi_app_container
    expose:
      - 8000
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:1.29.1
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi_app